// This file is part of Attesta.
// Copyright (C) 2026 The Attesta Contributors
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Provides utility functions.
 *
 * @module
 */

import { persistentHash, Bytes32Descriptor } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import { LivenessStatus, type Ledger } from '../common-types.js';

/**
 * Generates a buffer containing a series of randomly generated bytes.
 *
 * @param length The number of bytes to generate.
 * @returns A `Uint8Array` representing `length` randomly generated bytes.
 */
export const randomBytes = (length: number): Uint8Array => {
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);
  return bytes;
};

/**
 * Derives the same pseudonymous public issuer id the contract computes as
 * `persistentHash(issuerSecret)` (see `issuerIdOf` in attesta.compact), off-chain, from
 * an issuer's secret. Used by the issuer panel to know what to register in the
 * SIMULATED trust list via `setTrustedIssuer`, without needing an on-chain round trip.
 */
export const deriveIssuerId = (issuerSecret: Uint8Array): Uint8Array =>
  persistentHash<Uint8Array>(Bytes32Descriptor, issuerSecret);

/**
 * Derives the same nullifier the contract computes as `persistentHash(revocationSecret)`
 * (see `nullifierOf` in attesta.compact), off-chain, from an attestation's revocation
 * secret.
 */
export const deriveNullifierHash = (revocationSecret: Uint8Array): Uint8Array =>
  persistentHash<Uint8Array>(Bytes32Descriptor, revocationSecret);

/**
 * The subset of an attestation's fields a verifier needs, once it already holds them,
 * to track that attestation's live/expired/revoked status against a public ledger
 * snapshot — without submitting a new on-chain `proveLive` transaction every time.
 *
 * @remarks
 * `validFrom`/`validUntil` are only known to a verifier because `proveLive` disclosed
 * them (see attesta.compact, `proveLive` comment) the first time it ran for this
 * attestation; `issuerId`/`nullifierHash` come back from that same call (`issuerId`) or
 * are derivable locally (`nullifierHash`, from the revocation secret the verifier was
 * given out-of-band as part of the attestation's "proof packet"). None of this is raw
 * attestation data — it is exactly the set of fields `proveLive` itself would disclose.
 */
export type LivenessTrackingBundle = {
  readonly issuerId: Uint8Array;
  readonly nullifierHash: Uint8Array;
  readonly validFrom: bigint;
  readonly validUntil: bigint;
};

/**
 * Recomputes the exact same LIVE / EXPIRED / REVOKED / NOT_TRUSTED formula the
 * `proveLive` circuit enforces on-chain (attesta.compact — same precedence: revoked
 * beats window beats trust), but locally, from a public {@link Ledger} snapshot the app
 * already has (e.g. from the indexer's live contract-state subscription) plus a bundle
 * of already-disclosed fields for one specific attestation.
 *
 * @remarks
 * This is what lets the verifier panel reflect a revocation live — as the ledger
 * snapshot updates (see `AttestaAPI.state$`), the panel re-derives status locally
 * instead of prompting the user to sign a brand new transaction for every ledger tick.
 * It is not itself a fresh cryptographic proof: the UI must label it as a
 * ledger-tracked status, distinct from the moment an on-chain `proveLive` transaction
 * last actually ran (see IssuerPanel/VerifierPanel `LivenessBadge` usage). Kept generic
 * (ledger + bundle in, status out — no issuer/verifier-specific shape) so a future Wave
 * 2 auditor surface can reuse it unchanged.
 */
export const deriveLivenessStatus = (
  ledger: Ledger,
  bundle: LivenessTrackingBundle,
  nowSeconds: bigint,
): LivenessStatus => {
  const isRevoked = ledger.revokedNullifiers.member(bundle.nullifierHash);
  const withinWindow = nowSeconds >= bundle.validFrom && nowSeconds < bundle.validUntil;
  const isTrusted = ledger.trustedIssuers.member(bundle.issuerId);

  if (isRevoked) return LivenessStatus.REVOKED;
  if (!withinWindow) return LivenessStatus.EXPIRED;
  if (!isTrusted) return LivenessStatus.NOT_TRUSTED;
  return LivenessStatus.LIVE;
};
